# -*- coding: utf-8 -*-
"""Reddit_Language.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RKpsLPSTEqddFVhAWqyhuUsFQGHEwwnl
"""

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline

from fastai.text import *

data = load_data(path = Path('.'),file='data_lm_rdt.pkl',bs = 24)

# data.show_batch()

# learn = language_model_learner(data,AWD_LSTM)

# learn.lr_find()

# learn.recorder.plot()

# learn.fit_one_cycle(1,max_lr=slice(1,1e-02),moms=(0.8,0.7))

learn = load_learner(path = Path('.'),file="reddit.pkl")
TEXT = "Broccoli Bubblegum"
n_words = 7

print(learn.predict(TEXT,n_words=n_words))
